version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gpu-postgres
    restart: always
    environment:
      POSTGRES_DB: graphics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
